version: '3'
services:
  db:
    image: postgres:11.1
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: inno
      POSTGRES_PASSWORD: polis
    volumes:
      - ./data/postgres:/var/lib/postgresql/data